### PR TITLE
hopefully fixed stickers?

### PR DESCRIPTION
**Pull request by ksouthern**

### CODE REVIEW

**Comment by bahorn** [comment]
Screenshot from 2019-12-07 13-05-04


Seems to render like this until a resize event on Chromium `Version 78.0.3904.70 (Official Build) Built on Ubuntu , running on Ubuntu 19.10 (64-bit)`

Might need to trigger one?

**Comment by bahorn** [comment]
Also, probably need to fix what happens when you click the stickers, redirects to hexb.in still

**Comment by ksouthern** [comment]
> Screenshot from 2019-12-07 13-05-04
> 
> Seems to render like this until a resize event on Chromium `Version 78.0.3904.70 (Official Build) Built on Ubuntu , running on Ubuntu 19.10 (64-bit)`
> 
> Might need to trigger one?

I'm trying to work out how to do that now, any suggestions?

**Comment by bahorn** [comment]
```
window.dispatchEvent(new Event('resize'));
```
according to https://stackoverflow.com/questions/1818474/how-to-trigger-the-window-resize-event-in-javascript

though it might should require setting proper dimensions. need to check into how the hex grid works.

**Comment by ksouthern** [comment]
In that case, we should probably move over to github.com/hheu/hexbin to fix this

**Comment by bahorn** [comment]
Can't make an issue on that repo.

**Comment by robzwolf** [comment]
Have enabled issues on [hheu/hexbin](https://github.com/hheu/hexbin) @bahorn, should be able to continue this discussion there if you want.

**Comment by ksouthern** [comment]
@bahorn  I've reloaded the sub-module, so it now works on the deployment

**Pull request merged**
