### PR TITLE
Added T-shirt details to swag section 

### PR DESCRIPTION
**Pull request by tomMisson**
* Added info about vendors, t-shirt sizing, and when to order. 
* Linked to official guidelines for sticker standards and link to the tool for sticker generation as recommended by @wrussell1999

### CODE REVIEW

**Comment by robzwolf** [comment]
:100:

**Comment by tomMisson** [comment]
Thanks @robzwolf !! 🥇

**Comment by tomMisson** [comment]
@robzwolf can you reopen? just realised there's a formatting error. Sorry 😭

**Comment by robzwolf** [comment]
Reverted the PR using #93 @tomMisson. Make your fixes and then re-issue the whole PR :)

**Pull request merged**
