### PR TITLE
Add dates for JunctionX Exeter

### PR DESCRIPTION
**Pull request by robzwolf**
Source: https://facebook.com/events/2687054858028437/?ti=icl

### CODE REVIEW

**Comment by wrussell1999** [comment]
For University, you’ve put the society name down. Is it associated with Exeter Uni?

**Comment by ksouthern** [comment]
It is associated with the uni, and the location is within the uni (Roborough Studios)

**Comment by wrussell1999** [comment]
Worth changing to say Exeter Uni instead of the society for consistency on the website?

**Comment by bahorn** [comment]
That tends to be what we've done so far with all the other events, so i'd probably do that.

**Pull request merged**
