### PR TITLE
Add HHEU Unconference dates

### PR DESCRIPTION
**Pull request by robzwolf**
- Add past HHEU Unconference
- Suggest date for Feb 2020 HHEU Unconference

@aaronosher @bahorn

### CODE REVIEW

**Comment by bahorn** [comment]
Might be worth moving the unconference dates to a separate table. Was thinking of having them just below the about section.

Any idea where the February event will be hosted?

**Comment by robzwolf** [comment]
The main reason I've added the Feb 2020 Unconference in the same table is so that it's clear that that weekend is "booked" to avoid us clashing with any events.

**Comment by bahorn** [comment]
Ah good point.

**Comment by wrussell1999** [comment]
Maybe rename the table to be more generic to include events rather than just hackathons?

**Comment by robzwolf** [comment]
@wrussell1999 Have tweaked the wording slightly:
image

**Comment by robzwolf** [comment]
Merging this as I think we're all in agreement.

**Comment by wrussell1999** [comment]
@robzwolf that looks great! Thanks

**Pull request merged**
