### PR TITLE
Fixes #15 in HHEU/hexbin with some JS hack

### PR DESCRIPTION
**Pull request by bahorn**

### CODE REVIEW

**Comment by bahorn** [comment]
https://github.com/HHEU/hexbin/issues/15

Resolving this as it has to be done via this repo. Would have preferred to do it with just CSS, but not aware of a way of doing it. This trick only works if the hexbin and wiki are hosted on the same domain.

**Comment by bahorn** [comment]
Ok, this currently doesn't fix it as the whole iframe needs to load before the height is correct.

**Comment by bahorn** [comment]
Found http://davidjbradshaw.github.io/iframe-resizer

which is probably the best way of getting around this issue.

Need to go add one dependency to the stickers for this to work.

**Comment by bahorn** [comment]
Ok, this should be working now.

Tested with caching disabled + with the slow 3G connection in chrome dev tools, so reasonably confident in it.

**Comment by wrussell1999** [comment]
Screenshot 2019-12-11 at 06 18 17

Seems to work on an emulated iPhone 6/7/8 screen size

**Pull request merged**
